In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('ds1.csv')

In [3]:
df.head()

id   A   B Res
0   1  20  30   F
1   2  50  70   F
2   3  79   3   F
3   4  39  99   F
4   5  12  49   F

In [4]:
df.Res.value_counts()

F    859
T    143
Name: Res, dtype: int64

In [5]:
X = df.drop(['Res'],axis=1)
y = df.Res

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
X_train, X_test, y_train, y_test = train_test_split(
...     X, y, test_size=0.33, random_state=42)

In [8]:
import sklearn.linear_model as sl
import sklearn.tree as st

In [9]:
model = st.DecisionTreeClassifier()

In [10]:
model.fit(X_train,y_train)

DecisionTreeClassifier()

In [11]:
model.score(X_test,y_test)

0.7885196374622356

In [12]:
y_pred = model.predict(X_test)

In [13]:
import sklearn.metrics as mt

In [14]:
mt.confusion_matrix(y_test,y_pred)

array([[249,  37],
       [ 33,  12]])

# transform the data 

In [15]:
f = open("newds.csv","w")
f.write("A1,A2,B1,B2,Res\n")
a1 = 0 
b1 = 0
for k,v in df.iterrows():
    f.write("{0},{1},{2},{3},{4}\n".format(a1,v.A,b1,v.B,v.Res))
    a1 = v.A
    b1 = v.B
f.close()

In [16]:
df = pd.read_csv("newds.csv")

In [17]:
df.head()

A1  A2  B1  B2 Res
0   0  20   0  30   F
1  20  50  30  70   F
2  50  79  70   3   F
3  79  39   3  99   F
4  39  12  99  49   F

In [18]:
X = df.drop(['Res'],axis=1)
y = df.Res

In [19]:
from sklearn.model_selection import train_test_split

In [20]:
X_train, X_test, y_train, y_test = train_test_split(
...     X, y, test_size=0.33, random_state=42)

In [21]:
import sklearn.linear_model as sl
import sklearn.tree as st

In [22]:
model = st.DecisionTreeClassifier(min_samples_leaf=3)

In [23]:
model.fit(X_train,y_train)

DecisionTreeClassifier(min_samples_leaf=3)

In [24]:
model.score(X_test,y_test)

0.8640483383685801

In [25]:
y_pred = model.predict(X_test)

In [26]:
import sklearn.metrics as mt

In [27]:
mt.confusion_matrix(y_test,y_pred)

array([[265,  21],
       [ 24,  21]])

# try 2

In [28]:
df  = pd.read_csv("ds1.csv")

In [29]:
f = open("newds.csv","w")
f.write("A1,A2,A3,B1,B2,B3,Res\n")
a1 = 0 
b1 = 0
a2 = 0
b2 = 0
for k,v in df.iterrows():
    f.write("{0},{1},{2},{3},{4},{5},{6}\n".format(a1,a2,v.A,b1,b2,v.B,v.Res))
    a1 = a2
    b1 = b2
    a2 = v.A
    b2 = v.B
f.close()

In [30]:
df = pd.read_csv("newds.csv")

In [31]:
df.head()

A1  A2  A3  B1  B2  B3 Res
0   0   0  20   0   0  30   F
1   0  20  50   0  30  70   F
2  20  50  79  30  70   3   F
3  50  79  39  70   3  99   F
4  79  39  12   3  99  49   F

In [32]:
X = df.drop(['Res'],axis=1)
y = df.Res

In [33]:
from sklearn.model_selection import train_test_split

In [34]:
X_train, X_test, y_train, y_test = train_test_split(
...     X, y, test_size=0.33, random_state=42)

In [35]:
import sklearn.linear_model as sl
import sklearn.tree as st

In [36]:
model = st.DecisionTreeClassifier(min_samples_leaf=5)

In [37]:
model.fit(X_train,y_train)

DecisionTreeClassifier(min_samples_leaf=5)

In [38]:
model.score(X_test,y_test)

0.9335347432024169

In [39]:
y_pred = model.predict(X_test)

In [40]:
import sklearn.metrics as mt

In [41]:
mt.confusion_matrix(y_test,y_pred)

array([[279,   7],
       [ 15,  30]])

## Learn the difference 

In [42]:
df  = pd.read_csv("ds1.csv")

In [43]:
f = open("newds.csv","w")
f.write("A1,B1,Res\n")
a2 = 0
b2 = 0
for k,v in df.iterrows():
    f.write("{0},{1},{2}\n".format(v.A - a2,v.B-b2,v.Res))
    a2 = v.A
    b2 = v.B
f.close()

In [44]:
df = pd.read_csv("newds.csv")

In [45]:
df.head()

A1  B1 Res
0  20  30   F
1  30  40   F
2  29 -67   F
3 -40  96   F
4 -27 -50   F

In [46]:
X = df.drop(['Res'],axis=1)
y = df.Res

In [47]:
from sklearn.model_selection import train_test_split

In [48]:
X_train, X_test, y_train, y_test = train_test_split(
...     X, y, test_size=0.33, random_state=42)

In [49]:
import sklearn.linear_model as sl
import sklearn.tree as st

In [50]:
model = st.DecisionTreeClassifier(min_samples_leaf=5)

In [51]:
model.fit(X_train,y_train)

DecisionTreeClassifier(min_samples_leaf=5)

In [52]:
model.score(X_test,y_test)

0.8006042296072508

In [53]:
y_pred = model.predict(X_test)

In [54]:
import sklearn.metrics as mt

In [55]:
mt.confusion_matrix(y_test,y_pred)

array([[254,  32],
       [ 34,  11]])

# try 2

In [56]:
df  = pd.read_csv("ds1.csv")

In [57]:
f = open("newds.csv","w")
f.write("A1,A2,B1,B2,Res\n")
a1 = 0 
b1 = 0
a2 = 0
b2 = 0
for k,v in df.iterrows():
    f.write("{0},{1},{2},{3},{4}\n".format(a2 - a1,v.A - a2,b2 - b1,v.B-b2,v.Res))
    a1 = a2
    b1 = b2
    a2 = v.A
    b2 = v.B
f.close()

In [58]:
df = pd.read_csv("newds.csv")

In [59]:
df.head()

A1  A2  B1  B2 Res
0   0  20   0  30   F
1  20  30  30  40   F
2  30  29  40 -67   F
3  29 -40 -67  96   F
4 -40 -27  96 -50   F

In [60]:
X = df.drop(['Res'],axis=1)
y = df.Res

In [61]:
from sklearn.model_selection import train_test_split

In [62]:
X_train, X_test, y_train, y_test = train_test_split(
...     X, y, test_size=0.33, random_state=42)

In [63]:
import sklearn.linear_model as sl
import sklearn.tree as st

In [64]:
model = st.DecisionTreeClassifier(min_samples_leaf=5)

In [65]:
model.fit(X_train,y_train)

DecisionTreeClassifier(min_samples_leaf=5)

In [66]:
model.score(X_test,y_test)

0.9969788519637462

In [67]:
y_pred = model.predict(X_test)

In [68]:
import sklearn.metrics as mt

In [69]:
mt.confusion_matrix(y_test,y_pred)

array([[285,   1],
       [  0,  45]])